spring:
  kafka:
    consumer:
      properties:
        partition.assignment.strategy: org.apache.kafka.clients.consumer.CooperativeStickyAssignor

app:
  kafka:
    topic: study.events.assignment
    concurrency: 3
